package bmp_react;


	// Generated by Selenium IDE
	import org.junit.Test;
	import org.junit.Before;
	import org.junit.After;
	import static org.junit.Assert.*;
	import static org.hamcrest.CoreMatchers.is;
	import static org.hamcrest.core.IsNot.not;
	import org.openqa.selenium.By;
	import org.openqa.selenium.WebDriver;
	import org.openqa.selenium.firefox.FirefoxDriver;
	import org.openqa.selenium.chrome.ChromeDriver;
	import org.openqa.selenium.remote.RemoteWebDriver;
	import org.openqa.selenium.remote.DesiredCapabilities;
	import org.openqa.selenium.Dimension;
	import org.openqa.selenium.WebElement;
	import org.openqa.selenium.interactions.Actions;
	import org.openqa.selenium.support.ui.ExpectedConditions;
	import org.openqa.selenium.support.ui.WebDriverWait;
	import org.openqa.selenium.JavascriptExecutor;
	import org.openqa.selenium.Alert;
	import org.openqa.selenium.Keys;
	import java.util.*;
	import java.net.MalformedURLException;
	import java.net.URL;
	public class misbmp {

	 private WebDriver driver;

	    @Before
	    public void setUp() {
	    	  driver = new FirefoxDriver(); // Use class-level driver
	    }
	  @After
	  public void tearDown() {
	    driver.quit();
	  }
	  @Test
	  public void mis() {
	    driver.get("https://10.0.6.137:8443/bmp/login");
	    driver.manage().window().setSize(new Dimension(1280, 672));
	    driver.findElement(By.id("tsslogin-form_username")).click();
	    driver.findElement(By.id("tsslogin-form_username")).sendKeys("admin");
	    driver.findElement(By.id("tsslogin-form_password")).click();
	    driver.findElement(By.cssSelector(".anticon-eye-invisible > svg")).click();
	    driver.findElement(By.id("tsslogin-form_password")).click();
	    driver.findElement(By.id("tsslogin-form_password")).sendKeys("Admin123");
	    driver.findElement(By.cssSelector(".ant-btn")).click();
	    driver.findElement(By.linkText("Traffic")).click();
	    driver.findElement(By.linkText("SMSC Link")).click();
	    driver.findElement(By.linkText("SMSC Traffic")).click();
	  }
	}


