// Generated by Selenium IDE
package bmp_react;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

import io.github.bonigarcia.wdm.WebDriverManager;

import org.openqa.selenium.Dimension;
import java.util.HashMap;
import java.util.Map;


	import org.junit.Test;
	import org.openqa.selenium.By;
	import org.openqa.selenium.WebDriver;
	import org.openqa.selenium.firefox.FirefoxDriver;
	import io.github.bonigarcia.wdm.WebDriverManager;

	public class tracker{
	    private WebDriver driver;

	    @Before
	    public void setUp() {
	    	  driver = new FirefoxDriver(); // Use class-level driver
	    }

	    @Test
	    public void tracker() throws InterruptedException {
	        driver.get("https://10.0.6.137:8443/bmp/login");
	        driver.manage().window().setSize(new Dimension(1296, 688));
	        Thread.sleep(2000);

	        driver.findElement(By.id("tsslogin-form_username")).click();
	        driver.findElement(By.id("tsslogin-form_username")).sendKeys("admin");
	        Thread.sleep(2000);

	        driver.findElement(By.id("tsslogin-form_password")).click();
	        driver.findElement(By.id("tsslogin-form_password")).sendKeys("Admin123");
	        Thread.sleep(2000);

	        driver.findElement(By.cssSelector(".ant-btn")).click();
	        Thread.sleep(2000);

	        driver.findElement(By.linkText("Tracker")).click();
	        Thread.sleep(2000);

	        driver.findElement(By.id("TSSGUI_InputTextFieldStyle")).click();
	        driver.findElement(By.id("TSSGUI_InputTextFieldStyle")).sendKeys("555555555555");
	        Thread.sleep(2000);

	        driver.findElement(By.cssSelector(".form-group:nth-child(3) > #fieldSetDiv > #TSSGUI_InputTextFieldSetStyle #TSSGUI_InputTextFieldStyle")).click();
	        driver.findElement(By.cssSelector(".form-group:nth-child(3) > #fieldSetDiv > #TSSGUI_InputTextFieldSetStyle #TSSGUI_InputTextFieldStyle")).sendKeys("66666666666666");
	        Thread.sleep(2000);

	        driver.findElement(By.cssSelector(".form-group:nth-child(4) #TSSGUI_DateFieldSetStyle .fa")).click();
	        driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(2) > span")).click();
	        Thread.sleep(2000);

	        driver.findElement(By.cssSelector(".card-body")).click();
	        driver.findElement(By.cssSelector(".form-group:nth-child(5) .fa")).click();
	        driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(1) > span")).click();
	        //driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(3) > span")).click();
	        Thread.sleep(2000);

	        driver.findElement(By.cssSelector(".card-body")).click();
	        driver.findElement(By.cssSelector(".tss-primary-onhover-btn")).click();
	        Thread.sleep(2000);

	        driver.findElement(By.cssSelector(".swal2-confirm")).click();
	        Thread.sleep(2000);
	    }

	    @After
	    public void tearDown() {
	        driver.quit();
	    }
	}
